#ifndef EVM_CONFIG_H
#define EVM_CONFIG_H

#define CONFIG_EVM_REPL_DEV_NAME    "uart0"
#define CONFIG_EVM_MODULE_UART
#define CONFIG_EVM_MODULE_GPIO
#define CONFIG_EVM_MODULE_ADC
#define CONFIG_EVM_MODULE_TIMER
#define CONFIG_EVM_MODULE_REPL

#endif
