DEFINES += LV_LVGL_H_INCLUDE_SIMPLE

INCLUDEPATH +=  $$PWD/../../../components/lvgl/lvgl/

HEADERS += \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_disp.h \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_event.h \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_group.h \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_indev.h \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_indev_scroll.h \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_obj.h \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_obj_class.h \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_obj_draw.h \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_obj_pos.h \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_obj_scroll.h \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_obj_style.h \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_obj_style_gen.h \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_obj_tree.h \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_refr.h \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_theme.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_arc.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_img.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_label.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_layer.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_line.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_mask.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_rect.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_transform.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_triangle.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_img_buf.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_img_cache.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_img_decoder.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/sw/lv_draw_sw.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_blend.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_dither.h \
    $$PWD/../../../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_gradient.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/layouts/flex/lv_flex.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/layouts/grid/lv_grid.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/layouts/lv_layouts.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/lv_extra.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/themes/basic/lv_theme_basic.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/themes/default/lv_theme_default.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/themes/lv_themes.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/themes/mono/lv_theme_mono.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/animimg/lv_animimg.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/calendar/lv_calendar.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/calendar/lv_calendar_header_arrow.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/calendar/lv_calendar_header_dropdown.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/chart/lv_chart.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/colorwheel/lv_colorwheel.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/imgbtn/lv_imgbtn.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/keyboard/lv_keyboard.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/led/lv_led.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/list/lv_list.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/lv_widgets.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/menu/lv_menu.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/meter/lv_meter.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/msgbox/lv_msgbox.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/span/lv_span.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/spinbox/lv_spinbox.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/spinner/lv_spinner.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/tabview/lv_tabview.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/tileview/lv_tileview.h \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/win/lv_win.h \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font.h \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_fmt_txt.h \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_loader.h \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_symbol_def.h \
    $$PWD/../../../components/lvgl/lvgl/src/hal/lv_hal.h \
    $$PWD/../../../components/lvgl/lvgl/src/hal/lv_hal_disp.h \
    $$PWD/../../../components/lvgl/lvgl/src/hal/lv_hal_indev.h \
    $$PWD/../../../components/lvgl/lvgl/src/hal/lv_hal_tick.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_anim.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_anim_timeline.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_area.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_assert.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_async.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_bidi.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_color.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_fs.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_gc.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_ll.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_log.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_lru.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_math.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_mem.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_printf.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_style.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_style_gen.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_templ.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_timer.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_tlsf.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_txt.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_txt_ap.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_types.h \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_utils.h \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_arc.h \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_bar.h \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_btn.h \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_btnmatrix.h \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_canvas.h \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_checkbox.h \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_dropdown.h \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_img.h \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_label.h \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_line.h \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_objx_templ.h \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_roller.h \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_slider.h \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_switch.h \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_table.h \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_textarea.h

SOURCES += \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_disp.c \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_event.c \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_group.c \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_indev.c \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_indev_scroll.c \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_obj.c \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_obj_class.c \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_obj_draw.c \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_obj_pos.c \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_obj_scroll.c \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_obj_style.c \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_obj_style_gen.c \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_obj_tree.c \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_refr.c \
    $$PWD/../../../components/lvgl/lvgl/src/core/lv_theme.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_arc.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_img.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_label.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_layer.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_line.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_mask.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_rect.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_transform.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_draw_triangle.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_img_buf.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_img_cache.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/lv_img_decoder.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/sw/lv_draw_sw.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_arc.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_blend.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_dither.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_gradient.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_img.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_layer.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_letter.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_line.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_polygon.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_rect.c \
    $$PWD/../../../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_transform.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/layouts/flex/lv_flex.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/layouts/grid/lv_grid.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/lv_extra.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/themes/basic/lv_theme_basic.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/themes/default/lv_theme_default.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/themes/mono/lv_theme_mono.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/animimg/lv_animimg.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/calendar/lv_calendar.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/calendar/lv_calendar_header_arrow.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/calendar/lv_calendar_header_dropdown.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/chart/lv_chart.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/colorwheel/lv_colorwheel.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/imgbtn/lv_imgbtn.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/keyboard/lv_keyboard.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/led/lv_led.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/list/lv_list.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/menu/lv_menu.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/meter/lv_meter.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/msgbox/lv_msgbox.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/span/lv_span.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/spinbox/lv_spinbox.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/spinner/lv_spinner.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/tabview/lv_tabview.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/tileview/lv_tileview.c \
    $$PWD/../../../components/lvgl/lvgl/src/extra/widgets/win/lv_win.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_dejavu_16_persian_hebrew.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_fmt_txt.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_loader.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_10.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_12.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_12_subpx.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_14.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_16.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_18.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_20.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_22.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_24.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_26.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_28.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_28_compressed.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_30.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_32.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_34.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_36.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_38.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_40.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_42.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_44.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_46.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_48.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_montserrat_8.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_simsun_16_cjk.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_unscii_16.c \
    $$PWD/../../../components/lvgl/lvgl/src/font/lv_font_unscii_8.c \
    $$PWD/../../../components/lvgl/lvgl/src/hal/lv_hal_disp.c \
    $$PWD/../../../components/lvgl/lvgl/src/hal/lv_hal_indev.c \
    $$PWD/../../../components/lvgl/lvgl/src/hal/lv_hal_tick.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_anim.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_anim_timeline.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_area.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_async.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_bidi.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_color.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_fs.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_gc.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_ll.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_log.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_lru.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_math.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_mem.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_printf.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_style.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_style_gen.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_templ.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_timer.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_tlsf.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_txt.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_txt_ap.c \
    $$PWD/../../../components/lvgl/lvgl/src/misc/lv_utils.c \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_arc.c \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_bar.c \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_btn.c \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_btnmatrix.c \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_canvas.c \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_checkbox.c \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_dropdown.c \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_img.c \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_label.c \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_line.c \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_objx_templ.c \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_roller.c \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_slider.c \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_switch.c \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_table.c \
    $$PWD/../../../components/lvgl/lvgl/src/widgets/lv_textarea.c

