#ifndef EVM_MODULE_LVGL_H
#define EVM_MODULE_LVGL_H

#include "lvgl.h"

#define set_style_width(obj, v) lv_obj_set_style_width(obj, v, LV_PART_MAIN)
#define set_style_min_width(obj, v) lv_obj_set_style_min_width(obj, v, LV_PART_MAIN)
#define set_style_max_width(obj, v) lv_obj_set_style_max_width(obj, v, LV_PART_MAIN)
#define set_style_height(obj, v) lv_obj_set_style_height(obj, v, LV_PART_MAIN)
#define set_style_min_height(obj, v) lv_obj_set_style_min_height(obj, v, LV_PART_MAIN)
#define set_style_max_height(obj, v) lv_obj_set_style_max_height(obj, v, LV_PART_MAIN)
#define set_style_x(obj, v) lv_obj_set_style_x(obj, v, LV_PART_MAIN)
#define set_style_y(obj, v) lv_obj_set_style_y(obj, v, LV_PART_MAIN)
#define set_style_align(obj, v) lv_obj_set_style_align(obj, v, LV_PART_MAIN)
#define set_style_transform_width(obj, v) lv_obj_set_style_transform_width(obj, v, LV_PART_MAIN)
#define set_style_transform_height(obj, v) lv_obj_set_style_transform_height(obj, v, LV_PART_MAIN)
#define set_style_translate_x(obj, v) lv_obj_set_style_translate_x(obj, v, LV_PART_MAIN)
#define set_style_translate_y(obj, v) lv_obj_set_style_translate_y(obj, v, LV_PART_MAIN)
#define set_style_transform_zoom(obj, v) lv_obj_set_style_transform_zoom(obj, v, LV_PART_MAIN)
#define set_style_transform_pivot_x(obj, v) lv_obj_set_style_transform_pivot_x(obj, v, LV_PART_MAIN)
#define set_style_transform_pivot_y(obj, v) lv_obj_set_style_transform_pivot_y(obj, v, LV_PART_MAIN)
#define set_style_pad_top(obj, v) lv_obj_set_style_pad_top(obj, v, LV_PART_MAIN)
#define set_style_pad_bottom(obj, v) lv_obj_set_style_pad_bottom(obj, v, LV_PART_MAIN)
#define set_style_pad_left(obj, v) lv_obj_set_style_pad_left(obj, v, LV_PART_MAIN)
#define set_style_pad_right(obj, v) lv_obj_set_style_pad_right(obj, v, LV_PART_MAIN)
#define set_style_pad_row(obj, v) lv_obj_set_style_pad_row(obj, v, LV_PART_MAIN)
#define set_style_pad_column(obj, v) lv_obj_set_style_pad_column(obj, v, LV_PART_MAIN)
#define set_style_bg_color(obj, v) lv_obj_set_style_bg_color(obj, v, LV_PART_MAIN)
#define set_style_bg_opa(obj, v) lv_obj_set_style_bg_opa(obj, v, LV_PART_MAIN)
#define set_style_bg_grad_color(obj, v) lv_obj_set_style_bg_grad_color(obj, v, LV_PART_MAIN)
#define set_style_bg_grad_dir(obj, v) lv_obj_set_style_bg_grad_dir(obj, v, LV_PART_MAIN)
#define set_style_bg_main_stop(obj, v) lv_obj_set_style_bg_main_stop(obj, v, LV_PART_MAIN)
#define set_style_bg_grad_stop(obj, v) lv_obj_set_style_bg_grad_stop(obj, v, LV_PART_MAIN)
#define set_style_bg_dither_mode(obj, v) lv_obj_set_style_bg_dither_mode(obj, v, LV_PART_MAIN)
#define set_style_border_color(obj, v) lv_obj_set_style_border_color(obj, v, LV_PART_MAIN)
#define set_style_border_opa(obj, v) lv_obj_set_style_border_opa(obj, v, LV_PART_MAIN)
#define set_style_border_width(obj, v) lv_obj_set_style_border_width(obj, v, LV_PART_MAIN)
#define set_style_border_side(obj, v) lv_obj_set_style_border_side(obj, v, LV_PART_MAIN)
#define set_style_border_post(obj, v) lv_obj_set_style_border_post(obj, v, LV_PART_MAIN)
#define set_style_outline_width(obj, v) lv_obj_set_style_outline_width(obj, v, LV_PART_MAIN)
#define set_style_outline_color(obj, v) lv_obj_set_style_outline_color(obj, v, LV_PART_MAIN)
#define set_style_outline_opa(obj, v) lv_obj_set_style_outline_opa(obj, v, LV_PART_MAIN)
#define set_style_outline_pad(obj, v) lv_obj_set_style_outline_pad(obj, v, LV_PART_MAIN)
#define set_style_shadow_width(obj, v) lv_obj_set_style_shadow_width(obj, v, LV_PART_MAIN)
#define set_style_shadow_ofs_x(obj, v) lv_obj_set_style_shadow_ofs_x(obj, v, LV_PART_MAIN)
#define set_style_shadow_ofs_y(obj, v) lv_obj_set_style_shadow_ofs_y(obj, v, LV_PART_MAIN)
#define set_style_shadow_spread(obj, v) lv_obj_set_style_shadow_spread(obj, v, LV_PART_MAIN)
#define set_style_shadow_color(obj, v) lv_obj_set_style_shadow_color(obj, v, LV_PART_MAIN)
#define set_style_shadow_opa(obj, v) lv_obj_set_style_shadow_opa(obj, v, LV_PART_MAIN)
#define set_style_line_width(obj, v) lv_obj_set_style_line_width(obj, v, LV_PART_MAIN)
#define set_style_line_dash_width(obj, v) lv_obj_set_style_line_dash_width(obj, v, LV_PART_MAIN)
#define set_style_line_dash_gap(obj, v) lv_obj_set_style_line_dash_gap(obj, v, LV_PART_MAIN)
#define set_style_line_rounded(obj, v) lv_obj_set_style_line_rounded(obj, v, LV_PART_MAIN)
#define set_style_line_color(obj, v) lv_obj_set_style_line_color(obj, v, LV_PART_MAIN)
#define set_style_line_opa(obj, v) lv_obj_set_style_line_opa(obj, v, LV_PART_MAIN)
#define set_style_arc_width(obj, v) lv_obj_set_style_arc_width(obj, v, LV_PART_MAIN)
#define set_style_arc_rounded(obj, v) lv_obj_set_style_arc_rounded(obj, v, LV_PART_MAIN)
#define set_style_arc_color(obj, v) lv_obj_set_style_arc_color(obj, v, LV_PART_MAIN)
#define set_style_arc_opa(obj, v) lv_obj_set_style_arc_opa(obj, v, LV_PART_MAIN)
#define set_style_arc_indic_width(obj, v) lv_obj_set_style_arc_width(obj, v, LV_PART_INDICATOR)
#define set_style_arc_indic_color(obj, v) lv_obj_set_style_arc_color(obj, v, LV_PART_INDICATOR)
#define set_style_text_opa(obj, v) lv_obj_set_style_text_opa(obj, v, LV_PART_MAIN)
#define set_style_text_font(obj, v) lv_obj_set_style_text_font(obj, v, LV_PART_MAIN)
#define set_style_text_letter_space(obj, v) lv_obj_set_style_text_letter_space(obj, v, LV_PART_MAIN)
#define set_style_text_line_space(obj, v) lv_obj_set_style_text_line_space(obj, v, LV_PART_MAIN)
#define set_style_text_decor(obj, v) lv_obj_set_style_text_decor(obj, v, LV_PART_MAIN)
#define set_style_text_align(obj, v) lv_obj_set_style_text_align(obj, v, LV_PART_MAIN)
#define set_style_radius(obj, v) lv_obj_set_style_radius(obj, v, LV_PART_MAIN)
#define set_style_text_color(obj, v) lv_obj_set_style_text_color(obj, v, LV_PART_MAIN)

#endif
