DEFINES += LV_LVGL_H_INCLUDE_SIMPLE

INCLUDEPATH +=  $$PWD/../components/lvgl/lvgl/

HEADERS += \
    $$PWD/../components/lvgl/lvgl/examples/anim/lv_example_anim.h \
    $$PWD/../components/lvgl/lvgl/examples/arduino/LVGL_Arduino/LVGL_Arduino.ino \
    $$PWD/../components/lvgl/lvgl/examples/event/lv_example_event.h \
    $$PWD/../components/lvgl/lvgl/examples/get_started/lv_example_get_started.h \
    $$PWD/../components/lvgl/lvgl/examples/layouts/flex/lv_example_flex.h \
    $$PWD/../components/lvgl/lvgl/examples/layouts/grid/lv_example_grid.h \
    $$PWD/../components/lvgl/lvgl/examples/layouts/lv_example_layout.h \
    $$PWD/../components/lvgl/lvgl/examples/libs/bmp/lv_example_bmp.h \
    $$PWD/../components/lvgl/lvgl/examples/libs/ffmpeg/lv_example_ffmpeg.h \
    $$PWD/../components/lvgl/lvgl/examples/libs/freetype/lv_example_freetype.h \
    $$PWD/../components/lvgl/lvgl/examples/libs/gif/lv_example_gif.h \
    $$PWD/../components/lvgl/lvgl/examples/libs/lv_example_libs.h \
    $$PWD/../components/lvgl/lvgl/examples/libs/png/lv_example_png.h \
    $$PWD/../components/lvgl/lvgl/examples/libs/qrcode/lv_example_qrcode.h \
    $$PWD/../components/lvgl/lvgl/examples/libs/rlottie/lv_example_rlottie.h \
    $$PWD/../components/lvgl/lvgl/examples/libs/sjpg/lv_example_sjpg.h \
    $$PWD/../components/lvgl/lvgl/examples/lv_examples.h \
    $$PWD/../components/lvgl/lvgl/examples/others/fragment/lv_example_fragment.h \
    $$PWD/../components/lvgl/lvgl/examples/others/gridnav/lv_example_gridnav.h \
    $$PWD/../components/lvgl/lvgl/examples/others/ime/lv_example_ime_pinyin.h \
    $$PWD/../components/lvgl/lvgl/examples/others/imgfont/lv_example_imgfont.h \
    $$PWD/../components/lvgl/lvgl/examples/others/lv_example_others.h \
    $$PWD/../components/lvgl/lvgl/examples/others/monkey/lv_example_monkey.h \
    $$PWD/../components/lvgl/lvgl/examples/others/msg/lv_example_msg.h \
    $$PWD/../components/lvgl/lvgl/examples/others/snapshot/lv_example_snapshot.h \
    $$PWD/../components/lvgl/lvgl/examples/porting/lv_port_disp_template.h \
    $$PWD/../components/lvgl/lvgl/examples/porting/lv_port_fs_template.h \
    $$PWD/../components/lvgl/lvgl/examples/porting/lv_port_indev_template.h \
    $$PWD/../components/lvgl/lvgl/examples/scroll/lv_example_scroll.h \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style.h \
    $$PWD/../components/lvgl/lvgl/examples/widgets/lv_example_widgets.h \
    $$PWD/../components/lvgl/lvgl/src/core/lv_disp.h \
    $$PWD/../components/lvgl/lvgl/src/core/lv_event.h \
    $$PWD/../components/lvgl/lvgl/src/core/lv_group.h \
    $$PWD/../components/lvgl/lvgl/src/core/lv_indev.h \
    $$PWD/../components/lvgl/lvgl/src/core/lv_indev_scroll.h \
    $$PWD/../components/lvgl/lvgl/src/core/lv_obj.h \
    $$PWD/../components/lvgl/lvgl/src/core/lv_obj_class.h \
    $$PWD/../components/lvgl/lvgl/src/core/lv_obj_draw.h \
    $$PWD/../components/lvgl/lvgl/src/core/lv_obj_pos.h \
    $$PWD/../components/lvgl/lvgl/src/core/lv_obj_scroll.h \
    $$PWD/../components/lvgl/lvgl/src/core/lv_obj_style.h \
    $$PWD/../components/lvgl/lvgl/src/core/lv_obj_style_gen.h \
    $$PWD/../components/lvgl/lvgl/src/core/lv_obj_tree.h \
    $$PWD/../components/lvgl/lvgl/src/core/lv_refr.h \
    $$PWD/../components/lvgl/lvgl/src/core/lv_theme.h \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw.h \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_arc.h \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_img.h \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_label.h \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_layer.h \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_line.h \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_mask.h \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_rect.h \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_transform.h \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_triangle.h \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_img_buf.h \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_img_cache.h \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_img_decoder.h \
    $$PWD/../components/lvgl/lvgl/src/draw/sw/lv_draw_sw.h \
    $$PWD/../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_blend.h \
    $$PWD/../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_dither.h \
    $$PWD/../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_gradient.h \
    $$PWD/../components/lvgl/lvgl/src/extra/layouts/flex/lv_flex.h \
    $$PWD/../components/lvgl/lvgl/src/extra/layouts/grid/lv_grid.h \
    $$PWD/../components/lvgl/lvgl/src/extra/layouts/lv_layouts.h \
    $$PWD/../components/lvgl/lvgl/src/extra/lv_extra.h \
    $$PWD/../components/lvgl/lvgl/src/extra/themes/basic/lv_theme_basic.h \
    $$PWD/../components/lvgl/lvgl/src/extra/themes/default/lv_theme_default.h \
    $$PWD/../components/lvgl/lvgl/src/extra/themes/lv_themes.h \
    $$PWD/../components/lvgl/lvgl/src/extra/themes/mono/lv_theme_mono.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/animimg/lv_animimg.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/calendar/lv_calendar.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/calendar/lv_calendar_header_arrow.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/calendar/lv_calendar_header_dropdown.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/chart/lv_chart.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/colorwheel/lv_colorwheel.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/imgbtn/lv_imgbtn.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/keyboard/lv_keyboard.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/led/lv_led.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/list/lv_list.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/lv_widgets.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/menu/lv_menu.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/meter/lv_meter.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/msgbox/lv_msgbox.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/span/lv_span.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/spinbox/lv_spinbox.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/spinner/lv_spinner.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/tabview/lv_tabview.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/tileview/lv_tileview.h \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/win/lv_win.h \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font.h \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_fmt_txt.h \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_loader.h \
    $$PWD/../components/lvgl/lvgl/src/font/lv_symbol_def.h \
    $$PWD/../components/lvgl/lvgl/src/hal/lv_hal.h \
    $$PWD/../components/lvgl/lvgl/src/hal/lv_hal_disp.h \
    $$PWD/../components/lvgl/lvgl/src/hal/lv_hal_indev.h \
    $$PWD/../components/lvgl/lvgl/src/hal/lv_hal_tick.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_anim.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_anim_timeline.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_area.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_assert.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_async.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_bidi.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_color.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_fs.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_gc.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_ll.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_log.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_lru.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_math.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_mem.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_printf.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_style.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_style_gen.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_templ.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_timer.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_tlsf.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_txt.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_txt_ap.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_types.h \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_utils.h \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_arc.h \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_bar.h \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_btn.h \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_btnmatrix.h \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_canvas.h \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_checkbox.h \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_dropdown.h \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_img.h \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_label.h \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_line.h \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_objx_templ.h \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_roller.h \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_slider.h \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_switch.h \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_table.h \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_textarea.h

SOURCES += \
    $$PWD/../components/lvgl/lvgl/examples/anim/lv_example_anim_1.c \
    $$PWD/../components/lvgl/lvgl/examples/anim/lv_example_anim_2.c \
    $$PWD/../components/lvgl/lvgl/examples/anim/lv_example_anim_3.c \
    $$PWD/../components/lvgl/lvgl/examples/anim/lv_example_anim_timeline_1.c \
    $$PWD/../components/lvgl/lvgl/examples/assets/animimg001.c \
    $$PWD/../components/lvgl/lvgl/examples/assets/animimg002.c \
    $$PWD/../components/lvgl/lvgl/examples/assets/animimg003.c \
    $$PWD/../components/lvgl/lvgl/examples/assets/emoji/img_emoji_F617.c \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_caret_down.c \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_cogwheel_alpha16.c \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_cogwheel_argb.c \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_cogwheel_chroma_keyed.c \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_cogwheel_indexed16.c \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_cogwheel_rgb.c \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_hand.c \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_skew_strip.c \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_star.c \
    $$PWD/../components/lvgl/lvgl/examples/assets/imgbtn_left.c \
    $$PWD/../components/lvgl/lvgl/examples/assets/imgbtn_mid.c \
    $$PWD/../components/lvgl/lvgl/examples/assets/imgbtn_right.c \
    $$PWD/../components/lvgl/lvgl/examples/event/lv_example_event_1.c \
    $$PWD/../components/lvgl/lvgl/examples/event/lv_example_event_2.c \
    $$PWD/../components/lvgl/lvgl/examples/event/lv_example_event_3.c \
    $$PWD/../components/lvgl/lvgl/examples/event/lv_example_event_4.c \
    $$PWD/../components/lvgl/lvgl/examples/get_started/lv_example_get_started_1.c \
    $$PWD/../components/lvgl/lvgl/examples/get_started/lv_example_get_started_2.c \
    $$PWD/../components/lvgl/lvgl/examples/get_started/lv_example_get_started_3.c \
    $$PWD/../components/lvgl/lvgl/examples/layouts/flex/lv_example_flex_1.c \
    $$PWD/../components/lvgl/lvgl/examples/layouts/flex/lv_example_flex_2.c \
    $$PWD/../components/lvgl/lvgl/examples/layouts/flex/lv_example_flex_3.c \
    $$PWD/../components/lvgl/lvgl/examples/layouts/flex/lv_example_flex_4.c \
    $$PWD/../components/lvgl/lvgl/examples/layouts/flex/lv_example_flex_5.c \
    $$PWD/../components/lvgl/lvgl/examples/layouts/flex/lv_example_flex_6.c \
    $$PWD/../components/lvgl/lvgl/examples/layouts/grid/lv_example_grid_1.c \
    $$PWD/../components/lvgl/lvgl/examples/layouts/grid/lv_example_grid_2.c \
    $$PWD/../components/lvgl/lvgl/examples/layouts/grid/lv_example_grid_3.c \
    $$PWD/../components/lvgl/lvgl/examples/layouts/grid/lv_example_grid_4.c \
    $$PWD/../components/lvgl/lvgl/examples/layouts/grid/lv_example_grid_5.c \
    $$PWD/../components/lvgl/lvgl/examples/layouts/grid/lv_example_grid_6.c \
    $$PWD/../components/lvgl/lvgl/examples/libs/bmp/lv_example_bmp_1.c \
    $$PWD/../components/lvgl/lvgl/examples/libs/ffmpeg/lv_example_ffmpeg_1.c \
    $$PWD/../components/lvgl/lvgl/examples/libs/ffmpeg/lv_example_ffmpeg_2.c \
    $$PWD/../components/lvgl/lvgl/examples/libs/freetype/lv_example_freetype_1.c \
    $$PWD/../components/lvgl/lvgl/examples/libs/gif/img_bulb_gif.c \
    $$PWD/../components/lvgl/lvgl/examples/libs/gif/lv_example_gif_1.c \
    $$PWD/../components/lvgl/lvgl/examples/libs/png/img_wink_png.c \
    $$PWD/../components/lvgl/lvgl/examples/libs/png/lv_example_png_1.c \
    $$PWD/../components/lvgl/lvgl/examples/libs/qrcode/lv_example_qrcode_1.c \
    $$PWD/../components/lvgl/lvgl/examples/libs/rlottie/lv_example_rlottie_1.c \
    $$PWD/../components/lvgl/lvgl/examples/libs/rlottie/lv_example_rlottie_2.c \
    $$PWD/../components/lvgl/lvgl/examples/libs/rlottie/lv_example_rlottie_approve.c \
    $$PWD/../components/lvgl/lvgl/examples/libs/sjpg/lv_example_sjpg_1.c \
    $$PWD/../components/lvgl/lvgl/examples/others/fragment/lv_example_fragment_1.c \
    $$PWD/../components/lvgl/lvgl/examples/others/fragment/lv_example_fragment_2.c \
    $$PWD/../components/lvgl/lvgl/examples/others/gridnav/lv_example_gridnav_1.c \
    $$PWD/../components/lvgl/lvgl/examples/others/gridnav/lv_example_gridnav_2.c \
    $$PWD/../components/lvgl/lvgl/examples/others/gridnav/lv_example_gridnav_3.c \
    $$PWD/../components/lvgl/lvgl/examples/others/gridnav/lv_example_gridnav_4.c \
    $$PWD/../components/lvgl/lvgl/examples/others/ime/lv_example_ime_pinyin_1.c \
    $$PWD/../components/lvgl/lvgl/examples/others/ime/lv_example_ime_pinyin_2.c \
    $$PWD/../components/lvgl/lvgl/examples/others/imgfont/lv_example_imgfont_1.c \
    $$PWD/../components/lvgl/lvgl/examples/others/monkey/lv_example_monkey_1.c \
    $$PWD/../components/lvgl/lvgl/examples/others/monkey/lv_example_monkey_2.c \
    $$PWD/../components/lvgl/lvgl/examples/others/monkey/lv_example_monkey_3.c \
    $$PWD/../components/lvgl/lvgl/examples/others/msg/lv_example_msg_1.c \
    $$PWD/../components/lvgl/lvgl/examples/others/msg/lv_example_msg_2.c \
    $$PWD/../components/lvgl/lvgl/examples/others/msg/lv_example_msg_3.c \
    $$PWD/../components/lvgl/lvgl/examples/others/snapshot/lv_example_snapshot_1.c \
    $$PWD/../components/lvgl/lvgl/examples/porting/lv_port_disp_template.c \
    $$PWD/../components/lvgl/lvgl/examples/porting/lv_port_fs_template.c \
    $$PWD/../components/lvgl/lvgl/examples/porting/lv_port_indev_template.c \
    $$PWD/../components/lvgl/lvgl/examples/scroll/lv_example_scroll_1.c \
    $$PWD/../components/lvgl/lvgl/examples/scroll/lv_example_scroll_2.c \
    $$PWD/../components/lvgl/lvgl/examples/scroll/lv_example_scroll_3.c \
    $$PWD/../components/lvgl/lvgl/examples/scroll/lv_example_scroll_4.c \
    $$PWD/../components/lvgl/lvgl/examples/scroll/lv_example_scroll_5.c \
    $$PWD/../components/lvgl/lvgl/examples/scroll/lv_example_scroll_6.c \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_1.c \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_10.c \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_11.c \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_12.c \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_13.c \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_14.c \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_15.c \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_2.c \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_3.c \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_4.c \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_5.c \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_6.c \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_7.c \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_8.c \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_9.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/animimg/lv_example_animimg_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/arc/lv_example_arc_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/arc/lv_example_arc_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/bar/lv_example_bar_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/bar/lv_example_bar_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/bar/lv_example_bar_3.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/bar/lv_example_bar_4.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/bar/lv_example_bar_5.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/bar/lv_example_bar_6.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/btn/lv_example_btn_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/btn/lv_example_btn_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/btn/lv_example_btn_3.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_3.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/calendar/lv_example_calendar_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/canvas/lv_example_canvas_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/canvas/lv_example_canvas_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_3.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_4.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_5.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_6.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_7.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_8.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_9.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/checkbox/lv_example_checkbox_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/checkbox/lv_example_checkbox_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/colorwheel/lv_example_colorwheel_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/dropdown/lv_example_dropdown_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/dropdown/lv_example_dropdown_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/dropdown/lv_example_dropdown_3.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/img/lv_example_img_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/img/lv_example_img_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/img/lv_example_img_3.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/img/lv_example_img_4.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/imgbtn/lv_example_imgbtn_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/keyboard/lv_example_keyboard_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/label/lv_example_label_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/label/lv_example_label_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/label/lv_example_label_3.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/label/lv_example_label_4.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/label/lv_example_label_5.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/led/lv_example_led_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/line/lv_example_line_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/list/lv_example_list_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/list/lv_example_list_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/menu/lv_example_menu_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/menu/lv_example_menu_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/menu/lv_example_menu_3.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/menu/lv_example_menu_4.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/menu/lv_example_menu_5.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/meter/lv_example_meter_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/meter/lv_example_meter_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/meter/lv_example_meter_3.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/meter/lv_example_meter_4.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/msgbox/lv_example_msgbox_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/obj/lv_example_obj_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/obj/lv_example_obj_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/roller/lv_example_roller_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/roller/lv_example_roller_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/roller/lv_example_roller_3.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/slider/lv_example_slider_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/slider/lv_example_slider_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/slider/lv_example_slider_3.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/span/lv_example_span_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/spinbox/lv_example_spinbox_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/spinner/lv_example_spinner_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/switch/lv_example_switch_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/table/lv_example_table_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/table/lv_example_table_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/tabview/lv_example_tabview_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/tabview/lv_example_tabview_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/textarea/lv_example_textarea_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/textarea/lv_example_textarea_2.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/textarea/lv_example_textarea_3.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/tileview/lv_example_tileview_1.c \
    $$PWD/../components/lvgl/lvgl/examples/widgets/win/lv_example_win_1.c \
    $$PWD/../components/lvgl/lvgl/src/core/lv_disp.c \
    $$PWD/../components/lvgl/lvgl/src/core/lv_event.c \
    $$PWD/../components/lvgl/lvgl/src/core/lv_group.c \
    $$PWD/../components/lvgl/lvgl/src/core/lv_indev.c \
    $$PWD/../components/lvgl/lvgl/src/core/lv_indev_scroll.c \
    $$PWD/../components/lvgl/lvgl/src/core/lv_obj.c \
    $$PWD/../components/lvgl/lvgl/src/core/lv_obj_class.c \
    $$PWD/../components/lvgl/lvgl/src/core/lv_obj_draw.c \
    $$PWD/../components/lvgl/lvgl/src/core/lv_obj_pos.c \
    $$PWD/../components/lvgl/lvgl/src/core/lv_obj_scroll.c \
    $$PWD/../components/lvgl/lvgl/src/core/lv_obj_style.c \
    $$PWD/../components/lvgl/lvgl/src/core/lv_obj_style_gen.c \
    $$PWD/../components/lvgl/lvgl/src/core/lv_obj_tree.c \
    $$PWD/../components/lvgl/lvgl/src/core/lv_refr.c \
    $$PWD/../components/lvgl/lvgl/src/core/lv_theme.c \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw.c \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_arc.c \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_img.c \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_label.c \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_layer.c \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_line.c \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_mask.c \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_rect.c \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_transform.c \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_draw_triangle.c \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_img_buf.c \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_img_cache.c \
    $$PWD/../components/lvgl/lvgl/src/draw/lv_img_decoder.c \
    $$PWD/../components/lvgl/lvgl/src/draw/sw/lv_draw_sw.c \
    $$PWD/../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_arc.c \
    $$PWD/../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_blend.c \
    $$PWD/../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_dither.c \
    $$PWD/../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_gradient.c \
    $$PWD/../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_img.c \
    $$PWD/../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_layer.c \
    $$PWD/../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_letter.c \
    $$PWD/../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_line.c \
    $$PWD/../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_polygon.c \
    $$PWD/../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_rect.c \
    $$PWD/../components/lvgl/lvgl/src/draw/sw/lv_draw_sw_transform.c \
    $$PWD/../components/lvgl/lvgl/src/extra/layouts/flex/lv_flex.c \
    $$PWD/../components/lvgl/lvgl/src/extra/layouts/grid/lv_grid.c \
    $$PWD/../components/lvgl/lvgl/src/extra/lv_extra.c \
    $$PWD/../components/lvgl/lvgl/src/extra/themes/basic/lv_theme_basic.c \
    $$PWD/../components/lvgl/lvgl/src/extra/themes/default/lv_theme_default.c \
    $$PWD/../components/lvgl/lvgl/src/extra/themes/mono/lv_theme_mono.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/animimg/lv_animimg.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/calendar/lv_calendar.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/calendar/lv_calendar_header_arrow.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/calendar/lv_calendar_header_dropdown.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/chart/lv_chart.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/colorwheel/lv_colorwheel.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/imgbtn/lv_imgbtn.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/keyboard/lv_keyboard.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/led/lv_led.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/list/lv_list.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/menu/lv_menu.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/meter/lv_meter.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/msgbox/lv_msgbox.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/span/lv_span.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/spinbox/lv_spinbox.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/spinner/lv_spinner.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/tabview/lv_tabview.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/tileview/lv_tileview.c \
    $$PWD/../components/lvgl/lvgl/src/extra/widgets/win/lv_win.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_dejavu_16_persian_hebrew.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_fmt_txt.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_loader.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_10.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_12.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_12_subpx.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_14.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_16.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_18.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_20.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_22.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_24.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_26.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_28.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_28_compressed.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_30.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_32.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_34.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_36.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_38.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_40.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_42.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_44.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_46.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_48.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_montserrat_8.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_simsun_16_cjk.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_unscii_16.c \
    $$PWD/../components/lvgl/lvgl/src/font/lv_font_unscii_8.c \
    $$PWD/../components/lvgl/lvgl/src/hal/lv_hal_disp.c \
    $$PWD/../components/lvgl/lvgl/src/hal/lv_hal_indev.c \
    $$PWD/../components/lvgl/lvgl/src/hal/lv_hal_tick.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_anim.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_anim_timeline.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_area.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_async.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_bidi.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_color.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_fs.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_gc.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_ll.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_log.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_lru.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_math.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_mem.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_printf.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_style.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_style_gen.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_templ.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_timer.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_tlsf.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_txt.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_txt_ap.c \
    $$PWD/../components/lvgl/lvgl/src/misc/lv_utils.c \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_arc.c \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_bar.c \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_btn.c \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_btnmatrix.c \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_canvas.c \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_checkbox.c \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_dropdown.c \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_img.c \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_label.c \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_line.c \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_objx_templ.c \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_roller.c \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_slider.c \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_switch.c \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_table.c \
    $$PWD/../components/lvgl/lvgl/src/widgets/lv_textarea.c

SOURCES += \
    $$PWD/../components/lvgl/lvgl/src/extra/libs/fsdrv/lv_fs_stdio.c

DISTFILES += \
    $$PWD/../components/lvgl/lvgl/examples/anim/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/anim/lv_example_anim_1.py \
    $$PWD/../components/lvgl/lvgl/examples/anim/lv_example_anim_2.py \
    $$PWD/../components/lvgl/lvgl/examples/anim/lv_example_anim_3.py \
    $$PWD/../components/lvgl/lvgl/examples/anim/lv_example_anim_timeline_1.py \
    $$PWD/../components/lvgl/lvgl/examples/assets/animimg001.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/animimg002.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/animimg003.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/caret_down.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/emoji/F600.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/font/lv_font_simsun_16_cjk.fnt \
    $$PWD/../components/lvgl/lvgl/examples/assets/font/montserrat-16.fnt \
    $$PWD/../components/lvgl/lvgl/examples/assets/font/montserrat-22.fnt \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_caret_down.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_cogwheel_argb.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_cogwheel_chroma_keyed.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_cogwheel_indexed16.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_cogwheel_rgb.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_hand_hour.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_hand_min.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_skew_strip.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_skew_strip_80x20_argb8888.fnt \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_star.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/img_strip.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/imgbtn_left.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/imgbtn_mid.png \
    $$PWD/../components/lvgl/lvgl/examples/assets/imgbtn_right.png \
    $$PWD/../components/lvgl/lvgl/examples/event/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/event/lv_example_event_1.py \
    $$PWD/../components/lvgl/lvgl/examples/event/lv_example_event_2.py \
    $$PWD/../components/lvgl/lvgl/examples/event/lv_example_event_3.py \
    $$PWD/../components/lvgl/lvgl/examples/get_started/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/get_started/lv_example_get_started_1.py \
    $$PWD/../components/lvgl/lvgl/examples/get_started/lv_example_get_started_2.py \
    $$PWD/../components/lvgl/lvgl/examples/get_started/lv_example_get_started_3.py \
    $$PWD/../components/lvgl/lvgl/examples/header.py \
    $$PWD/../components/lvgl/lvgl/examples/layouts/flex/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/layouts/flex/lv_example_flex_1.py \
    $$PWD/../components/lvgl/lvgl/examples/layouts/flex/lv_example_flex_2.py \
    $$PWD/../components/lvgl/lvgl/examples/layouts/flex/lv_example_flex_3.py \
    $$PWD/../components/lvgl/lvgl/examples/layouts/flex/lv_example_flex_4.py \
    $$PWD/../components/lvgl/lvgl/examples/layouts/flex/lv_example_flex_5.py \
    $$PWD/../components/lvgl/lvgl/examples/layouts/flex/lv_example_flex_6.py \
    $$PWD/../components/lvgl/lvgl/examples/layouts/grid/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/layouts/grid/lv_example_grid_1.py \
    $$PWD/../components/lvgl/lvgl/examples/layouts/grid/lv_example_grid_2.py \
    $$PWD/../components/lvgl/lvgl/examples/layouts/grid/lv_example_grid_3.py \
    $$PWD/../components/lvgl/lvgl/examples/layouts/grid/lv_example_grid_4.py \
    $$PWD/../components/lvgl/lvgl/examples/layouts/grid/lv_example_grid_5.py \
    $$PWD/../components/lvgl/lvgl/examples/layouts/grid/lv_example_grid_6.py \
    $$PWD/../components/lvgl/lvgl/examples/libs/bmp/example_16bit.bmp \
    $$PWD/../components/lvgl/lvgl/examples/libs/bmp/example_24bit.bmp \
    $$PWD/../components/lvgl/lvgl/examples/libs/bmp/example_32bit.bmp \
    $$PWD/../components/lvgl/lvgl/examples/libs/bmp/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/libs/bmp/lv_example_bmp_1.py \
    $$PWD/../components/lvgl/lvgl/examples/libs/ffmpeg/birds.mp4 \
    $$PWD/../components/lvgl/lvgl/examples/libs/ffmpeg/ffmpeg.png \
    $$PWD/../components/lvgl/lvgl/examples/libs/ffmpeg/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/libs/freetype/Lato-Regular.ttf \
    $$PWD/../components/lvgl/lvgl/examples/libs/freetype/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/libs/freetype/lv_example_freetype_1.py \
    $$PWD/../components/lvgl/lvgl/examples/libs/gif/bulb.gif \
    $$PWD/../components/lvgl/lvgl/examples/libs/gif/img_bulb_gif.py \
    $$PWD/../components/lvgl/lvgl/examples/libs/gif/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/libs/gif/lv_example_gif_1.py \
    $$PWD/../components/lvgl/lvgl/examples/libs/png/img_wink_png.py \
    $$PWD/../components/lvgl/lvgl/examples/libs/png/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/libs/png/lv_example_png_1.py \
    $$PWD/../components/lvgl/lvgl/examples/libs/png/wink.png \
    $$PWD/../components/lvgl/lvgl/examples/libs/qrcode/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/libs/qrcode/lv_example_qrcode_1.py \
    $$PWD/../components/lvgl/lvgl/examples/libs/rlottie/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/libs/rlottie/lv_example_rlottie_1.py \
    $$PWD/../components/lvgl/lvgl/examples/libs/rlottie/lv_example_rlottie_2.py \
    $$PWD/../components/lvgl/lvgl/examples/libs/rlottie/lv_example_rlottie_approve.json \
    $$PWD/../components/lvgl/lvgl/examples/libs/rlottie/lv_example_rlottie_approve.py \
    $$PWD/../components/lvgl/lvgl/examples/libs/sjpg/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/libs/sjpg/lv_example_sjpg_1.py \
    $$PWD/../components/lvgl/lvgl/examples/libs/sjpg/small_image.sjpg \
    $$PWD/../components/lvgl/lvgl/examples/lv_examples.mk \
    $$PWD/../components/lvgl/lvgl/examples/others/fragment/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/others/gridnav/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/others/ime/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/others/imgfont/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/others/monkey/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/others/msg/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/others/snapshot/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/others/snapshot/lv_example_snapshot_1.py \
    $$PWD/../components/lvgl/lvgl/examples/scroll/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/scroll/lv_example_scroll_1.py \
    $$PWD/../components/lvgl/lvgl/examples/scroll/lv_example_scroll_2.py \
    $$PWD/../components/lvgl/lvgl/examples/scroll/lv_example_scroll_3.py \
    $$PWD/../components/lvgl/lvgl/examples/scroll/lv_example_scroll_4.py \
    $$PWD/../components/lvgl/lvgl/examples/scroll/lv_example_scroll_5.py \
    $$PWD/../components/lvgl/lvgl/examples/scroll/lv_example_scroll_6.py \
    $$PWD/../components/lvgl/lvgl/examples/styles/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_1.py \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_10.py \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_11.py \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_12.py \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_13.py \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_14.py \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_2.py \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_3.py \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_4.py \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_5.py \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_6.py \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_7.py \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_8.py \
    $$PWD/../components/lvgl/lvgl/examples/styles/lv_example_style_9.py \
    $$PWD/../components/lvgl/lvgl/examples/test_ex.sh \
    $$PWD/../components/lvgl/lvgl/examples/widgets/animimg/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/animimg/lv_example_animimg_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/arc/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/arc/lv_example_arc_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/arc/lv_example_arc_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/bar/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/bar/lv_example_bar_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/bar/lv_example_bar_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/bar/lv_example_bar_3.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/bar/lv_example_bar_4.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/bar/lv_example_bar_5.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/bar/lv_example_bar_6.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/bar/test.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/btn/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/btn/lv_example_btn_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/btn/lv_example_btn_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/btn/lv_example_btn_3.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/btnmatrix/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_3.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/calendar/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/calendar/lv_example_calendar_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/canvas/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/canvas/lv_example_canvas_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/canvas/lv_example_canvas_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_3.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_4.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_5.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_6.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_7.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_8.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/chart/lv_example_chart_9.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/checkbox/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/checkbox/lv_example_checkbox_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/colorwheel/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/colorwheel/lv_example_colorwheel_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/dropdown/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/dropdown/lv_example_dropdown_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/dropdown/lv_example_dropdown_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/dropdown/lv_example_dropdown_3.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/img/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/img/lv_example_img_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/img/lv_example_img_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/img/lv_example_img_3.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/img/lv_example_img_4.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/imgbtn/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/imgbtn/lv_example_imgbtn_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/keyboard/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/keyboard/lv_example_keyboard_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/label/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/label/lv_example_label_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/label/lv_example_label_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/label/lv_example_label_3.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/label/lv_example_label_5.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/led/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/led/lv_example_led_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/line/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/line/lv_example_line_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/list/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/list/lv_example_list_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/list/lv_example_list_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/list/test.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/menu/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/menu/lv_example_menu_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/menu/lv_example_menu_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/menu/lv_example_menu_3.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/menu/lv_example_menu_4.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/meter/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/meter/lv_example_meter_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/meter/lv_example_meter_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/meter/lv_example_meter_3.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/meter/lv_example_meter_4.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/msgbox/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/msgbox/lv_example_msgbox_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/obj/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/obj/lv_example_obj_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/obj/lv_example_obj_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/roller/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/roller/lv_example_roller_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/roller/lv_example_roller_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/roller/lv_example_roller_3.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/slider/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/slider/lv_example_slider_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/slider/lv_example_slider_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/slider/lv_example_slider_3.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/span/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/span/lv_example_span_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/spinbox/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/spinbox/lv_example_spinbox_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/spinner/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/spinner/lv_example_spinner_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/switch/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/switch/lv_example_switch_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/table/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/table/lv_example_table_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/table/lv_example_table_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/tabview/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/tabview/lv_example_tabview_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/tabview/lv_example_tabview_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/textarea/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/textarea/lv_example_textarea_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/textarea/lv_example_textarea_2.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/textarea/lv_example_textarea_3.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/tileview/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/tileview/lv_example_tileview_1.py \
    $$PWD/../components/lvgl/lvgl/examples/widgets/win/index.rst \
    $$PWD/../components/lvgl/lvgl/examples/widgets/win/lv_example_win_1.py

