/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

volatile PikaObj *__pikaMain;
PikaObj *pikaScriptInit(void){
    __platform_printf("======[pikascript packages installed]======\r\n");
    pks_printVersion();
    __platform_printf("PikaStdLib==latest\r\n");
    __platform_printf("pika_lvgl==latest\r\n");
    __platform_printf("===========================================\r\n");
    PikaObj* pikaMain = newRootObj("pikaMain", New_PikaMain);
    __pikaMain = pikaMain;
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(pikaMain,
            "import PikaStdLib as std\n"
            "import pika_lvgl as lv\n"
            "from PikaStdLib import MemChecker\n"
            "mem = MemChecker()\n"
            "mem.now()\n"
            "class Element:\n"
            "    def __init__(self):\n"
            "        self.obj = None\n"
            "        self.parent = None\n"
            "        self.onclick = None\n"
            "    \n"
            "    def render(self):\n"
            "        pass\n"
            "    def clear(self):\n"
            "        pass\n"
            "    def bind(self, attribute, key):\n"
            "        pass\n"
            "    def id(self, v=None):\n"
            "        pass\n"
            "    def top(self, v=None):\n"
            "        pass\n"
            "    def left(self, v=None):\n"
            "        pass\n"
            "    def width(self, v=None):\n"
            "        pass\n"
            "    def height(self, v=None):\n"
            "        pass\n"
            "class TextElement(Element):\n"
            "    def __init__(self, element=None):\n"
            "        super().__init__()\n"
            "        if element is None:\n"
            "            self.obj = lv.label(lv.scr_act())\n"
            "        else:\n"
            "            self.obj = lv_label(element.obj)\n"
            "        self.__text = ''\n"
            "    def value(self, v=None):\n"
            "        if v is None:\n"
            "            return self.__text\n"
            "        else:\n"
            "            print(v)\n"
            "            self.__text = v\n"
            "            self.obj.set_text(v)\n"
            "class DivElement(Element):\n"
            "    def __init__(self, element=None):\n"
            "        super().__init__()\n"
            "        if element is None:\n"
            "            self.obj = lv.label(lv.scr_act())\n"
            "        else:\n"
            "            self.obj = lv_label(element.obj)\n"
            "id0 = TextElement()\n"
            "id0.value('hello EVM')\n"
            "\n");
#else 
    obj_runModule((PikaObj*)pikaMain, "main");
#endif
    return pikaMain;
}

