/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

volatile PikaObj *__pikaMain;
PikaObj *pikaScriptInit(void){
    __platform_printf("======[pikascript packages installed]======\r\n");
    pks_printVersion();
    __platform_printf("PikaStdLib==latest\r\n");
    __platform_printf("pika_lvgl==latest\r\n");
    __platform_printf("===========================================\r\n");
    PikaObj* pikaMain = newRootObj("pikaMain", New_PikaMain);
    __pikaMain = pikaMain;
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(pikaMain,
            "import PikaStdLib as std\n"
            "import pika_lvgl as lv\n"
            "from PikaStdLib import MemChecker\n"
            "mem = MemChecker()\n"
            "mem.now()\n"
            "def drag_event_handler(e):\n"
            "    obj = e.get_target()\n"
            "    indev = lv.indev_get_act()\n"
            "    vect = lv.point_t()\n"
            "    indev.get_vect(vect)\n"
            "    x = obj.get_x() + vect.x\n"
            "    y = obj.get_y() + vect.y\n"
            "    obj.set_pos(x, y)\n"
            "    mem.now()\n"
            "#\n"
            "# Make an object dragable.\n"
            "#\n"
            "obj = lv.obj(lv.scr_act())\n"
            "obj.set_size(150, 100)\n"
            "obj.add_event_cb(drag_event_handler, lv.EVENT.PRESSING, None)\n"
            "label = lv.label(obj)\n"
            "label.set_text(\"Drag me\")\n"
            "label.center()\n"
            "\n");
#else 
    obj_runModule((PikaObj*)pikaMain, "main");
#endif
    return pikaMain;
}

