# for module compiling
import os
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
evm_dir = cwd + '/../../../../../'
src = Split('''
''')

CPPPATH = [evm_dir + '/include', '../']

AddDepend('EVM_USE_MUJS')

group = DefineGroup('EVM', src, depend = [''], LIBS = [''], CCFLAGS = '', CPPPATH = CPPPATH, LIBPATH=[''])

Return('group')
